apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello2
spec:
  selector:
    matchLabels:
      app: hello2
      version: 2.0.0
  replicas: 2
  template:
    metadata:
      labels:
        app: hello2
        version: 2.0.0
    spec:
      containers:
      - name: hello2
        image: "nginx:1.14.2"
        env:
        - name: "PORT"
          value: "8080"
