apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: NodePort
  selector:
    app: hello2
    version: 2.0.0
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 32000
